config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :games do
    resources :moves
  end

end

app/models/board.rb
class Board
  attr_accessor :grid

  def initialize
     @grid = [nil, nil, nil, nil, nil, nil, nil, nil, nil]
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessor :current_user
  has_many :moves
  belongs_to :player1, class_name: 'User'
  belongs_to :player2, class_name: 'User'

#win combinations
  def self.check_win_combos(noughts, crosses)
    wins = [[0, 1, 2], [0, 4, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [2, 4, 6], [3, 4, 5], [6, 7, 8]]
    @win = false
    wins.each do |win|
      if (noughts & win).length == 3
        @win = true
      elsif (crosses & win).length == 3
        @win = true
      end
    end
    @win
  end

  def self.check_draw(noughts, crosses)
    if (noughts + crosses).length == 9
      true
    end
  end

  def self.gather_noughts(game_id)
    game = Game.find(game_id)
    noughts = game.moves.where(mark: 'o')
    noughts.map {|move| move.position }
  end

  def self.gather_crosses(game_id)
    game = Game.find(game_id)
    noughts = game.moves.where(mark: 'x')
    noughts.map {|move| move.position }
  end

#computer methods
  

  
end










  
 

app/models/move.rb
class Move < ActiveRecord::Base
  attr_accessor :player1
  belongs_to :user
  belongs_to :game

  def self.find_mark(game_id)
   game = Game.find(game_id)
    if game.moves.present?
      if game.moves.last.mark == "x"
        "o"
      else
        "x"
      end
    else
      "x"
    end
  end

  def self.computer_move(game_id)
    game = Game.find(game_id)
    positions_taken = game.moves.map { |move| move.position }
    board = (0..8).to_a
    available = board - positions_taken
    available.sample
  end





      
    
   
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :moves
  has_many :games_as_player1, foreign_key: :player1_id, class_name: 'Game'
  has_many :games_as_player2, foreign_key: :player2_id, class_name: 'Game'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    new_game_path
  end

  def after_sign_out_path_for(resource)
    new_game_path
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    
    if @game.save
      redirect_to game_path(@game)
    else
      render 'new'
    end
  end

  def show
    @game = Game.find(params[:id])
    @board = Board.new
    @move = Move.new

    #build board moves
    @game.moves.each do |move|
      @board.grid[move.position] = move.mark
    end
    #gather x positions
    noughts = Game.gather_noughts(params[:id])
    crosses = Game.gather_crosses(params[:id])
    #check for win
    if Game.check_win_combos(noughts, crosses)
      @winner =  "Winner!"
      @game.completed = true
      @game.winner = @game.moves.last.user.email
    end
    #check for draw but right now only all spaces
    if Game.check_draw(noughts, crosses)
      @draw = "Boo...Cat's Game"
      @game.winner = 'draw'
    end



    

    


  end

  private
  def game_params
    params.require(:game).permit(:winner, :completed, :player1_id, :player2_id, :player1_mark, :player2_mark)
  end

end

app/controllers/moves_controller.rb
class MovesController < ApplicationController

  before_action :authenticate_user!

  def index
  end

  def new
    @move = Move.new
  end

  def create
    @game = Game.find(params[:game_id])
    @move = Move.new(move_params)
    @move.mark = Move.find_mark(params[:game_id])
    
    # if @game.player2_id == 3
    #   @move = Move.new(mark: 'o', position: Move.computer_move(params[:game_id]), user_id: 3)
    # else
    #   @move = Move.new(move_params)
    #   @move.mark = Move.find_mark(params[:game_id])
    # end

    if @move.save
      redirect_to game_path(params[:game_id])
    else
      flash.alert = 'Oops...Try again!'
    end
  end

  def show
    @game = Game.find(@move.game_id)
    @move = Move.new
  end

  def update
  end


  private
  def move_params
    params.require(:move).permit(:mark, :position, :game_id, :user_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user!
  
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_winlosedraw.html.haml
- if @winner
  %h1= "#{Move.last.user.email} is the #{@winner}"
- else
  %h1= @draw

app/views/games/index.html.haml
.row.leaderboard
  .small-6.large-centered.columns
    %h1 Leaderboard
    %h2 Colin

app/views/games/new.html.haml
.row.new-game
  .small-6.large-centered.columns
    %h2 Who would you like to play?
    = form_for @game do |f|
      .row.select-game
        .small-6.large-centered.columns
          %label Human
          = f.collection_select :player2_id, User.all, :id, :email
      .row.select-game
        .small-6.large-centered.columns
          = f.hidden_field :player1_mark, value: 'x'
          = f.hidden_field :player2_mark, value: 'o'
          = f.hidden_field :player1_id, value: current_user.id
          = f.hidden_field :completed, value: false
      .row.select-game
        .small-6.large-centered.columns
          = f.submit "Let's Play!", class: "button round"

app/views/games/show.html.haml
.board-show
  .row
    .win-message
      %h1= render 'winlosedraw'
  .row
    = form_for [@game, @move] do |f|
      - unless @board.grid.all?
        - @board.grid.each_with_index do |mark, index|
          .large-4.columns.board-cell
            - if mark.nil?
              = f.hidden_field :game_id, value: @game.id
              = f.hidden_field :user_id, value: current_user.id
              = f.label "position_#{index}", index
              = f.radio_button :position, index
            - else
              .cell-mark
                = f.label "#{mark}"
        = f.submit "Submit Move", class: "button round"
      - else
        %h1 Game Over.
        %h3= link_to('New Game', new_game_path)

app/views/layouts/application.html.haml
!!! 5
%html{ lang: "en" }
  %head
    %meta{ charset: "utf-8" }
    -# %meta{ name: "viewport", content="width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "foundation-rails"
    %link{ rel: "stylesheet", href: "css/foundation.css" }
    %link{ href: 'https://fonts.googleapis.com/css?family=Montserrat', rel: 'stylesheet', type: 'text/css'}
    %link{ rel: "stylesheet", href: "css/app.css" }

    %script{ src: "js/vendor/modernizr.js" }

    = stylesheet_link_tag "application" 
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %header
      %nav.top-bar{ role: "navigation" }
        %ul.title-area
          %li.name
            %h1= link_to('TicTacToe', root_path)
          -# <!-- <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li> -->
        %section.top-bar-section
          -# <!-- Right Nav Section -->
          %ul.right
            %li.active
              = link_to('New Game', new_game_path)
            %li.active
              - if user_signed_in?
                = link_to('Logout', destroy_user_session_path, :method => :delete)
              - else
                %li.divider
                  %li.active
                    = link_to('Login', new_user_session_path)
                %li.divider
                  %li.active
                    = link_to('Register', new_user_registration_path)
            %li.has-dropdown
              %a{ href: "#" } More
              %ul.dropdown
                %li= link_to('Leaderboard', games_path)
      .notice-alert
        %p.notice= notice
        %p.alert= alert
   
      -# <!-- <div class="icon-bar five-up">
        %a.item{ aria-label="home" }
          %i.fi-home

    = yield

app/views/welcome/index.html.haml
.row.home
  .small-6.large-centered.columns
    %h1 How 'bout a game of Tic Tac Toe?
    %h3= link_to('New Game', new_game_path)